### ISSUE TITLE
/replace does not remove tags

### ISSUE THREAD

**Issue by patrickjmccarty** [Nukesor/sticker-finder#23]
I tried using the /replace command after sending a sticker. It says "Sticker tags replaced." but it does not actually remove the tags that I omitted.

I noticed that the /replace command is also not documented in the README, so is this feature just not ready yet?

**Comment by Nukesor** [comment]
This is a relatively new feature and I wanted to test/check how well the new tagging functionality works, since this was added in the context of this change:
`Tags will now be added to the existing tags, instead of replacing the old ones.`

I guess, that I could add it to the help and the docs.

**Comment by Nukesor** [comment]
I just tried the replace command and everything seems to work fine.
Could you please describe how to reproduce this bug?

**Comment by Nukesor** [comment]
On a second look, I already had a test for this in place :D
This makes me even more confident, that this might be some other issue

**Comment by pressRtowin** [comment]
I am experiencing this too. It happens when {newtags} is a subset of {existing tags}. For instance, if a sticker has tags "1", "2", "3", and "4", and you wish to remove "4", you cannot simply /replace 1 2 3. You must first replace with something entirely different like /replace 5, and then /replace 1 2 3.

**Comment by Nukesor** [comment]
Found it. That was a sneaky one :D
