### ISSUE TITLE
Add tag sticker pack function

### ISSUE THREAD

**Issue by TilCreator** [Nukesor/sticker-finder#29]
There are many sticker packs that don't have a very descriptive name.
For example ["Lyra"](https://t.me/addstickers/LyraMLP) won't come up in a search for "mlp", "pony" or similar.
This could be fixed by adding tags to sticker *packs* that get inherited by all stickers.
There seams to be something similar, but I think it is only used to tag packs "fur" or "nsfw" and seams to be not allowed by normal users. (Didn't read the code jet.)

**Comment by Nukesor** [comment]
There is absolutely no tag sticker_set function right now.

I'm still not sure, if I want this feature, since general descriptions of sticker packs should be the task of the sticker set name/title.

A tag_sticker_set function will be definitely abused, since users already tend to spam tags.
They add 10 tags and copy paste spam them for each sticker of the set.

Stickers should be tagged carefully, each sticker with it's own tags (general tags, expression, text, meta tags, etc). Adding a function for adding tags to a whole sticker set will most likely result in low effort and low quality tags all over the place (which also makes it way harder to review everything for me)

**Comment by TilCreator** [comment]
I would implement it so that sticker sets have their own tags and not add tags to all stickers of the pack. But I do understand your concerns and my implementation idea is also more complex.

If an add tag to all stickers function is not too hard to implement, it could maybe be a nice admin feature.

**Comment by Nukesor** [comment]
It's definitely not hard to implement. Would definitely be a nice admin feature, but should be only used when absolutely necessary.

**Comment by Nukesor** [comment]
Closing for now
