### ISSUE TITLE
Add tag alias and implication

### ISSUE THREAD

**Issue by TilCreator** [Nukesor/sticker-finder#30]
Tag alias:
Automatically searches for tags with the same meaning, too.
Aliases are set by users.
For example:
- Search "vixen" also searches for "fox female" and the other way around
- "wolf" <-> "lupine"
- "hug" <-> "hugging"
<br>

Tag implication:
Only difference is that implications work only one way.
For example:
- Search "cat" also searches for "kitty"
- "fox" -> "red_fox"

**Comment by Nukesor** [comment]
Boi. This is some advanced user stuff :D

I definitely see the advantages of this, but TBH I don't see myself or many other users using this.
If you like to add this feature to the bot, I would be happy to review and add it, but I don't think I'll implement it myself.

It would be great, if there were a more general/automatic mechanism for searching related words, but I'm not deep into search optimization yet...

Too many aliases could also become a problem, since fuzzy search with many search words is suuuper slow right now.

**Comment by TilCreator** [comment]
I am quite spoiled from more advanced search and tagging systems ( e621.net , ... ). ^^
So this would be overkill for this project, but if I can find the time (someday ^^) I will try to implement it.

**Comment by Nukesor** [comment]
Closing for now. Feel free to reopen, if you find some time to reimplement.
You'll probably need some help with the queries, they are by far the most complex stuff I've ever written :D
