### ISSUE TITLE
Basic boolean terms in search?

### ISSUE THREAD

**Issue by stilez** [Nukesor/sticker-finder#36]
I just tried searching for stickers of cat in a cage, but the results were flooded out by stickers of Nicholas Cage, and other things. Its a constant problem really for all kinds of sticker search.

It would really help.if the search understood basic booleans:  AND, OR, NOT, (), "LITERAL PHRASE", for those who want to use more.exact search.

This shouldn't be hard to.add, because all of those are SQL primitives as well. So no parser is needed - just detect if SQL rejects the text as a WHERE clause (or returns an error to the query) because its not syntactic, and let SQL handle it internally.  Input sanitising would also be unaffected, because the only additional non alphabetic characters used are ( ) " '.  And of course, nested or mixed quotes shouldn't be meaningful in the search text, so one can convert double quotes to.single on input, meaning that SQL quoted string handling wouldn't be needed either.

This would really be helpful, because then you could do fast accurate sticker finds easy, so they can be used in real-time during chats. And, of course, it would be transparent (not breaking anything else) if not used.

Any chance? It would be really good! Thank you!!

**Comment by Nukesor** [comment]
First of all, this would add a lot of complexity. Feel free to look into the query building code. It's huge and frickin complex. Simply excluding tags won't work, since we also try to match sticker set titles/names and there's also fuzzy search.

You could try to implement this behaviour, but I also don't see a huge benefit from it.
If you add words to your search, the stickers with the most matching tags will be on top.
In your case this means that there most likely are no cat stickers which the tag `cage`. Otherwise they would appear on top and `nicolas cage` sticker packs would have a lower search score.

If there are any problems with the current search and things don't appear, when they should, the score calculation system probably needs a little bit of adjustments. In this case, please send me the sticker file id of the affected sticker(s) and I'll investigate the issue.

You can get the file id of a sticker by replying to the sticker with `/show_id` in a private conversation with the Sticker Finder

**Comment by Nukesor** [comment]
And another thing:
Passing user input through withouth any input validation/sanitation is a horrible idea.
Please inform yourself about SQL injection attacks, before you suggest anybody to expose themself to these kinds of attacks.
